#!/bin/bash

check_error()
{
  if [ $? -ne 0 ]; then
    echo "ERROR on >>>>> "$1"!!"
    exit 2
  fi
}

work_dir="/home/j2play/pogoejabberd/ejabberd-debmaker/ejabberd/src/"

cd $work_dir
check_error "EJABBERDBUILD - CD"
./configure --prefix=/home/j2play/ejabberd"
check_error "EJABBERDBUILD - CONFIGURE"
make
check_error "EJABBERDBUILD - MAKE"
make install
check_error "EJABBERDBUILD - MAKE INSTALL"
